### ISSUE TITLE
Milestones and ToDo list for version 2.0.0

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#138]
# This is just a list of things that are planned to be done for future releases until version 2.0.0 is finally available.

# v 1.9.7.1

- [x] Update to target SDK 25.
- [x] Update all libraries.
- [x] App will open 2x faster now (maybe a bit more) (the tasks, like request one, will still take some time, but the app will be usable faster).
- [x] Removed some options basically nobody was using.
- [x] Removed icons based changelog.
- [x] Removed option to change app theme from inside the app. (You still can choose the default theme from the already existing 4 themes: light, dark, day/night, and transparent).
- [x] Smoother icons previews section, and fixed issue that made icons overlay others.
- [x] Added a soft gradient in toolbar and wallpaper viewer, for better icons visibility.
- [x] Minor fix and improvement for color extraction from icons and wallpapers.
- [x] Wallpapers have a new look to improve wallpaper visibility.
- [x] Added a new wallpaper viewer design, which is fullscreen and has a FAB. (The previous design will stay so you can choose between them both).
- [x] Fixed issue with dialog to select wallpapers download location. (Thanks to Patrick Jung).
- [x] Implemented new way to setup changelog. Easier and more organized. (Thanks to Allan Wang).
- [x] Added code to prevent multiple clicks/taps in items. This will prevent multiple dialogs showing on top of others, or multiple actions running at the same time.
- [x] Now cards in home section can deal with all websites links (facebook, google+, play store, whatever you want). If link is to play store, that means it's for an app, if so, the app will check if such app is installed and launch the app instead of taking users to play store.
- [x] Notifications will work with Firebase now. It's easier to implement, works better, and it's free. Anyways, you will be able to disable it if you don't want to use it.
- [x] Now you can add as many cards as you want in credits section, as well as customize the buttons in each card easily. It uses a really similar way as Polar dashboard does. Thanks to Aidan Follestad for allowing me to use it.
- [x] Credits section will credit Allan Wang too. Many people has contributed to the project, and they are all already mentioned in the credits. But I think Allan deserves a card because he's the person that has helped me the most, and that's constantly open to help, and that's done about 22% of the commits, which contain many code improvements and additions.
I already mention all the people that has ever helped, and I'm thankful with all of them, but I really think Allan deserves it. 

- [ ] Fix wallpapers not applying.
- [ ] Make sure navigation bar hides again after dialogs appear in `AltWallpaperViewerActivity`.
- [ ] Fix crash after asking permissions when request FAB is pressed.
- [ ] Make Icon Requests generate `appmap.xml` and `theme_resources.xml` as it did before.
- [ ] Implement credits in Splash Screen. [Reference](https://www.reddit.com/r/IconShowcase/comments/5a1ybh/considering_to_add_this_small_detail_in_apps/)

# v 1.9.7.2

- [ ] Implement launcher shortcuts.

# v 1.9.7.3

- [ ] Implement new Apply section/layout.

# v 1.9.7.4

- [ ] Fix requests time limit.

# v 1.9.7.5

- [ ] Fix wallpapers refresh button.
- [ ] Fix wallpapers columns amount changer.

# v 1.9.7.6

- [ ] Add themes back as user configuration.

# v 1.9.7.7

- [ ] Make notifications work with something else than Firebase.

# v 1.9.7.8

- [ ] Add icons based dialog. (This may or may not happen).

**Comment by justinkruit** [comment]
In addition to the v1.9.7.6 notification idea, I recommend OneSignal. Simple and free notification system, with Android Library support

**Comment by jahirfiquitiva** [comment]
@justinkruit
Thanks. That was exactly what I planned to use then. 😉
